export default function Example() {
  return (
    <>
    <div className="flex flex-col">
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      <div>ABCD</div>
      </div>
    </>
  )
}
